Test des modifications avec les fichiers approuvés

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,21 @@
 
+fileList=$(git diff --staged --name-only :^package-lock.json :^README.md :^client :^server :^.husky :^package.json)
 
-npx lint-staged
-pnpm test
+echo '----- Checking Root...'
 
+if [ ! -z "$fileList" ]
+then
+  echo "error: Unauthorized modifications\n"
+
+  echo "$fileList\n"
+
+  echo "use 'git restore --staged ...' to fix the problem"
+  echo "(and ask your instructor why you should not change these files)\n"
+
+  exit 1
+fi
+
+echo '----- Done!'
+
+npx validate-branch-name
+npm run lint
